parameters:
  azureSubscription: 'KMD Momentum Internal (77a2aca7-3b91-463d-9165-c6d0bb3689f9)'
  environmentNameSuffix: phoenix
  environmentAutoDelete: false
  instanceId: p12345
  resourceGroupLocation: westeurope

jobs:
  - deployment: deploy_momentum_mea_${{ parameters.environmentNameSuffix }}
    pool: { vmImage: 'windows-2019' }
    environment: momentum_mea_${{ parameters.environmentNameSuffix }}
    variables:
      AzureSubscription: ${{ parameters.azureSubscription }}
      EnvironmentAutoDelete: ${{ parameters.environmentAutoDelete }}
      InstanceId: ${{ parameters.instanceId }}
      ResourceGroupLocation: ${{ parameters.resourceGroupLocation }}
      ResourceGroupName: kmd-momentum-mea-${{ parameters.instanceId }}-rg

    strategy:
      runOnce:
        deploy:
          steps:
            - download: current

            - task: AzurePowerShell@4
              displayName: Deploy azure infrastructure
              inputs:
                azureSubscription: '$(AzureSubscription)'
                ScriptType: 'FilePath'
                ScriptPath: './deploy-infrastructure.ps1'
                ScriptArguments: -MarkForAutoDelete:('$(EnvironmentAutoDelete)' -eq 'true') -InstanceId '$(InstanceId)' -ResourceGroupLocation '$(ResourceGroupLocation)'
                azurePowerShellVersion: 'LatestVersion'
                errorActionPreference: 'stop'
                failOnStandardError: true
                pwsh: true
