trigger:
  branches:
    include:
    - master
    - dev
  paths:
    include:
    - Ui/*

stages:

- stage: deploy_phoenix
  jobs:
  - template: azure-pipelines-release-template.yml
    parameters:
      azureSubscription: 'KMD Momentum Internal (77a2aca7-3b91-463d-9165-c6d0bb3689f9)'
      environmentNameSuffix: phoenix
      instanceId: phoenix$(Build.BuildId)
      resourceGroupLocation: westeurope
      environmentAutoDelete: true